# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('userid', models.IntegerField()),
                ('appid', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('comment', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=10)),
                ('ico', models.TextField()),
                ('notifys', models.IntegerField(default=0)),
                ('deletable', models.IntegerField(default=0)),
                ('verify', models.IntegerField(default=1)),
                ('command', models.CharField(max_length=200)),
                ('browser', models.CharField(max_length=16, null=True)),
                ('src', models.CharField(max_length=255, null=True)),
                ('maximize', models.IntegerField(default=0)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('comment', models.TextField()),
                ('moditime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Persion',
            fields=[
                ('userid', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('nickname', models.CharField(max_length=20)),
                ('head', models.CharField(max_length=100)),
                ('autostart', models.BooleanField(default=True)),
                ('notifytype', models.IntegerField(default=0)),
                ('notifysound', models.BooleanField(default=True)),
                ('notifysoundtypt', models.CharField(default='Glass', max_length=16)),
                ('notifymaxnum', models.IntegerField(default=10)),
                ('notifymaxtime', models.IntegerField(default=10)),
                ('search', models.CharField(default='全部', max_length=20)),
                ('doubleclick', models.BooleanField(default=False)),
                ('screen', models.IntegerField(default=0)),
                ('wallpaper', models.CharField(max_length=255)),
            ],
        ),
    ]
